#Port
server:
  port: ${SERVER_PORT:9090}

#Application Name
spring:
  application:
    name: account-service

#DB Configuration
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
